name: Deploy to EC2

on:
  push:
    branches: [ main ]  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          # Add host key
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
          
          # Deploy
          ssh $EC2_USERNAME@$EC2_HOST '
            # Navigate to app directory
            cd /var/www/app
          
            # Pull code
            if [ -d ".git" ]; then
              git pull origin main
            else
              git clone https://github.com/yourusername/your-repo.git .
            fi
          
            # Reset permissions
            sudo chown -R ec2-user:ec2-user ./*
          
            # Install dependencies (uncomment what you need)
            # npm install
            # pip install -r requirements.txt
          
            # Restart service
            sudo systemctl restart your-service
            '
