name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Navigate to your project directory
            cd basic-chat-room-101

            # Pull the latest code from GitHub
            git pull origin main

            # Install dependencies
            npm install

            # Stop current PM2 processes (if any are running)
            pm2 stop angular-app || true
            pm2 stop node-server || true

            # Build the Angular app (production build)
            npm run build --prod

            # Start the Node.js server with PM2
            pm2 start server/server.js --name "node-server"

            # Start Angular app with PM2 (fixed quotes issue)
            pm2 start 'ng serve --host 0.0.0.0 --port 4242 --disable-host-check' --name "angular-app"

            # Optionally save the PM2 process list (for automatic restarts on reboot)
            pm2 save

            # Optionally: Set up PM2 to restart on server reboot
            pm2 startup systemd
            sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u $USER --hp /home/$USER
          EOF
